# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Commentoon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Kingfisher
  pod 'Kingfisher', '~> 7.6.2'

  # Kakao
  pod 'KakaoSDK'

  # Pods for Commentoon

end
